### PR TITLE
[CHK-1720] update-logo-ref

### PR DESCRIPTION
**Pull request by ciuffagianluca**
Update env refs to pagopa-logo

Depends on https://github.com/pagopa/pagopa-checkout-fe/pull/233/

#### List of Changes
Upate all helm refs and helm values

#### Motivation and Context
pagopa logo wasn't visible in gmail since it was an svg logo

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Fernando-Granato — COMMENTED** [review]
🚀

**Review by Fernando-Granato — APPROVED** [review]

**Review by Fernando-Granato — APPROVED** [review]
👉🏻 Remember to set release label  👀

**Comment by ciuffagianluca** [comment]
> 👉🏻 Remember to set release label 👀

missing patch label, can i create it?

**Review by MarcoAGreco — APPROVED** [review]
LGTM 🚀

**Pull request merged**
